// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/channelrole"
	"server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChannelRoleDelete is the builder for deleting a ChannelRole entity.
type ChannelRoleDelete struct {
	config
	hooks    []Hook
	mutation *ChannelRoleMutation
}

// Where appends a list predicates to the ChannelRoleDelete builder.
func (crd *ChannelRoleDelete) Where(ps ...predicate.ChannelRole) *ChannelRoleDelete {
	crd.mutation.Where(ps...)
	return crd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (crd *ChannelRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, crd.sqlExec, crd.mutation, crd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (crd *ChannelRoleDelete) ExecX(ctx context.Context) int {
	n, err := crd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (crd *ChannelRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelrole.Table, sqlgraph.NewFieldSpec(channelrole.FieldID, field.TypeInt))
	if ps := crd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, crd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	crd.mutation.done = true
	return affected, err
}

// ChannelRoleDeleteOne is the builder for deleting a single ChannelRole entity.
type ChannelRoleDeleteOne struct {
	crd *ChannelRoleDelete
}

// Where appends a list predicates to the ChannelRoleDelete builder.
func (crdo *ChannelRoleDeleteOne) Where(ps ...predicate.ChannelRole) *ChannelRoleDeleteOne {
	crdo.crd.mutation.Where(ps...)
	return crdo
}

// Exec executes the deletion query.
func (crdo *ChannelRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := crdo.crd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (crdo *ChannelRoleDeleteOne) ExecX(ctx context.Context) {
	if err := crdo.Exec(ctx); err != nil {
		panic(err)
	}
}
