// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/channel"
	"server/ent/predicate"
	"server/ent/room"
	"server/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (cu *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdateTime sets the "updateTime" field.
func (cu *ChannelUpdate) SetUpdateTime(t time.Time) *ChannelUpdate {
	cu.mutation.SetUpdateTime(t)
	return cu
}

// SetDeleteTime sets the "delete_time" field.
func (cu *ChannelUpdate) SetDeleteTime(t time.Time) *ChannelUpdate {
	cu.mutation.SetDeleteTime(t)
	return cu
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (cu *ChannelUpdate) SetNillableDeleteTime(t *time.Time) *ChannelUpdate {
	if t != nil {
		cu.SetDeleteTime(*t)
	}
	return cu
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (cu *ChannelUpdate) ClearDeleteTime() *ChannelUpdate {
	cu.mutation.ClearDeleteTime()
	return cu
}

// SetCode sets the "code" field.
func (cu *ChannelUpdate) SetCode(s string) *ChannelUpdate {
	cu.mutation.SetCode(s)
	return cu
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (cu *ChannelUpdate) SetNillableCode(s *string) *ChannelUpdate {
	if s != nil {
		cu.SetCode(*s)
	}
	return cu
}

// ClearCode clears the value of the "code" field.
func (cu *ChannelUpdate) ClearCode() *ChannelUpdate {
	cu.mutation.ClearCode()
	return cu
}

// SetName sets the "name" field.
func (cu *ChannelUpdate) SetName(s string) *ChannelUpdate {
	cu.mutation.SetName(s)
	return cu
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (cu *ChannelUpdate) AddRoomIDs(ids ...int64) *ChannelUpdate {
	cu.mutation.AddRoomIDs(ids...)
	return cu
}

// AddRooms adds the "rooms" edges to the Room entity.
func (cu *ChannelUpdate) AddRooms(r ...*Room) *ChannelUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddRoomIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (cu *ChannelUpdate) AddUserIDs(ids ...int64) *ChannelUpdate {
	cu.mutation.AddUserIDs(ids...)
	return cu
}

// AddUsers adds the "users" edges to the User entity.
func (cu *ChannelUpdate) AddUsers(u ...*User) *ChannelUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.AddUserIDs(ids...)
}

// SetOwnerUserID sets the "owner_user" edge to the User entity by ID.
func (cu *ChannelUpdate) SetOwnerUserID(id int64) *ChannelUpdate {
	cu.mutation.SetOwnerUserID(id)
	return cu
}

// SetOwnerUser sets the "owner_user" edge to the User entity.
func (cu *ChannelUpdate) SetOwnerUser(u *User) *ChannelUpdate {
	return cu.SetOwnerUserID(u.ID)
}

// Mutation returns the ChannelMutation object of the builder.
func (cu *ChannelUpdate) Mutation() *ChannelMutation {
	return cu.mutation
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (cu *ChannelUpdate) ClearRooms() *ChannelUpdate {
	cu.mutation.ClearRooms()
	return cu
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (cu *ChannelUpdate) RemoveRoomIDs(ids ...int64) *ChannelUpdate {
	cu.mutation.RemoveRoomIDs(ids...)
	return cu
}

// RemoveRooms removes "rooms" edges to Room entities.
func (cu *ChannelUpdate) RemoveRooms(r ...*Room) *ChannelUpdate {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveRoomIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (cu *ChannelUpdate) ClearUsers() *ChannelUpdate {
	cu.mutation.ClearUsers()
	return cu
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (cu *ChannelUpdate) RemoveUserIDs(ids ...int64) *ChannelUpdate {
	cu.mutation.RemoveUserIDs(ids...)
	return cu
}

// RemoveUsers removes "users" edges to User entities.
func (cu *ChannelUpdate) RemoveUsers(u ...*User) *ChannelUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cu.RemoveUserIDs(ids...)
}

// ClearOwnerUser clears the "owner_user" edge to the User entity.
func (cu *ChannelUpdate) ClearOwnerUser() *ChannelUpdate {
	cu.mutation.ClearOwnerUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChannelUpdate) Save(ctx context.Context) (int, error) {
	if err := cu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChannelUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ChannelUpdate) defaults() error {
	if _, ok := cu.mutation.UpdateTime(); !ok {
		if channel.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized channel.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := channel.UpdateDefaultUpdateTime()
		cu.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChannelUpdate) check() error {
	if v, ok := cu.mutation.Code(); ok {
		if err := channel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Channel.code": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Name(); ok {
		if err := channel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Channel.name": %w`, err)}
		}
	}
	if _, ok := cu.mutation.OwnerUserID(); cu.mutation.OwnerUserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Channel.owner_user"`)
	}
	return nil
}

func (cu *ChannelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt64))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdateTime(); ok {
		_spec.SetField(channel.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cu.mutation.DeleteTime(); ok {
		_spec.SetField(channel.FieldDeleteTime, field.TypeTime, value)
	}
	if cu.mutation.DeleteTimeCleared() {
		_spec.ClearField(channel.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := cu.mutation.Code(); ok {
		_spec.SetField(channel.FieldCode, field.TypeString, value)
	}
	if cu.mutation.CodeCleared() {
		_spec.ClearField(channel.FieldCode, field.TypeString)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if cu.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !cu.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedUsersIDs(); len(nodes) > 0 && !cu.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.OwnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerUserTable,
			Columns: []string{channel.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OwnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerUserTable,
			Columns: []string{channel.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMutation
}

// SetUpdateTime sets the "updateTime" field.
func (cuo *ChannelUpdateOne) SetUpdateTime(t time.Time) *ChannelUpdateOne {
	cuo.mutation.SetUpdateTime(t)
	return cuo
}

// SetDeleteTime sets the "delete_time" field.
func (cuo *ChannelUpdateOne) SetDeleteTime(t time.Time) *ChannelUpdateOne {
	cuo.mutation.SetDeleteTime(t)
	return cuo
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (cuo *ChannelUpdateOne) SetNillableDeleteTime(t *time.Time) *ChannelUpdateOne {
	if t != nil {
		cuo.SetDeleteTime(*t)
	}
	return cuo
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (cuo *ChannelUpdateOne) ClearDeleteTime() *ChannelUpdateOne {
	cuo.mutation.ClearDeleteTime()
	return cuo
}

// SetCode sets the "code" field.
func (cuo *ChannelUpdateOne) SetCode(s string) *ChannelUpdateOne {
	cuo.mutation.SetCode(s)
	return cuo
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (cuo *ChannelUpdateOne) SetNillableCode(s *string) *ChannelUpdateOne {
	if s != nil {
		cuo.SetCode(*s)
	}
	return cuo
}

// ClearCode clears the value of the "code" field.
func (cuo *ChannelUpdateOne) ClearCode() *ChannelUpdateOne {
	cuo.mutation.ClearCode()
	return cuo
}

// SetName sets the "name" field.
func (cuo *ChannelUpdateOne) SetName(s string) *ChannelUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// AddRoomIDs adds the "rooms" edge to the Room entity by IDs.
func (cuo *ChannelUpdateOne) AddRoomIDs(ids ...int64) *ChannelUpdateOne {
	cuo.mutation.AddRoomIDs(ids...)
	return cuo
}

// AddRooms adds the "rooms" edges to the Room entity.
func (cuo *ChannelUpdateOne) AddRooms(r ...*Room) *ChannelUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddRoomIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (cuo *ChannelUpdateOne) AddUserIDs(ids ...int64) *ChannelUpdateOne {
	cuo.mutation.AddUserIDs(ids...)
	return cuo
}

// AddUsers adds the "users" edges to the User entity.
func (cuo *ChannelUpdateOne) AddUsers(u ...*User) *ChannelUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.AddUserIDs(ids...)
}

// SetOwnerUserID sets the "owner_user" edge to the User entity by ID.
func (cuo *ChannelUpdateOne) SetOwnerUserID(id int64) *ChannelUpdateOne {
	cuo.mutation.SetOwnerUserID(id)
	return cuo
}

// SetOwnerUser sets the "owner_user" edge to the User entity.
func (cuo *ChannelUpdateOne) SetOwnerUser(u *User) *ChannelUpdateOne {
	return cuo.SetOwnerUserID(u.ID)
}

// Mutation returns the ChannelMutation object of the builder.
func (cuo *ChannelUpdateOne) Mutation() *ChannelMutation {
	return cuo.mutation
}

// ClearRooms clears all "rooms" edges to the Room entity.
func (cuo *ChannelUpdateOne) ClearRooms() *ChannelUpdateOne {
	cuo.mutation.ClearRooms()
	return cuo
}

// RemoveRoomIDs removes the "rooms" edge to Room entities by IDs.
func (cuo *ChannelUpdateOne) RemoveRoomIDs(ids ...int64) *ChannelUpdateOne {
	cuo.mutation.RemoveRoomIDs(ids...)
	return cuo
}

// RemoveRooms removes "rooms" edges to Room entities.
func (cuo *ChannelUpdateOne) RemoveRooms(r ...*Room) *ChannelUpdateOne {
	ids := make([]int64, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveRoomIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (cuo *ChannelUpdateOne) ClearUsers() *ChannelUpdateOne {
	cuo.mutation.ClearUsers()
	return cuo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (cuo *ChannelUpdateOne) RemoveUserIDs(ids ...int64) *ChannelUpdateOne {
	cuo.mutation.RemoveUserIDs(ids...)
	return cuo
}

// RemoveUsers removes "users" edges to User entities.
func (cuo *ChannelUpdateOne) RemoveUsers(u ...*User) *ChannelUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return cuo.RemoveUserIDs(ids...)
}

// ClearOwnerUser clears the "owner_user" edge to the User entity.
func (cuo *ChannelUpdateOne) ClearOwnerUser() *ChannelUpdateOne {
	cuo.mutation.ClearOwnerUser()
	return cuo
}

// Where appends a list predicates to the ChannelUpdate builder.
func (cuo *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Channel entity.
func (cuo *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	if err := cuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ChannelUpdateOne) defaults() error {
	if _, ok := cuo.mutation.UpdateTime(); !ok {
		if channel.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized channel.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := channel.UpdateDefaultUpdateTime()
		cuo.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChannelUpdateOne) check() error {
	if v, ok := cuo.mutation.Code(); ok {
		if err := channel.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Channel.code": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Name(); ok {
		if err := channel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Channel.name": %w`, err)}
		}
	}
	if _, ok := cuo.mutation.OwnerUserID(); cuo.mutation.OwnerUserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Channel.owner_user"`)
	}
	return nil
}

func (cuo *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt64))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdateTime(); ok {
		_spec.SetField(channel.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.DeleteTime(); ok {
		_spec.SetField(channel.FieldDeleteTime, field.TypeTime, value)
	}
	if cuo.mutation.DeleteTimeCleared() {
		_spec.ClearField(channel.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := cuo.mutation.Code(); ok {
		_spec.SetField(channel.FieldCode, field.TypeString, value)
	}
	if cuo.mutation.CodeCleared() {
		_spec.ClearField(channel.FieldCode, field.TypeString)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if cuo.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedRoomsIDs(); len(nodes) > 0 && !cuo.mutation.RoomsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RoomsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.RoomsTable,
			Columns: []string{channel.RoomsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !cuo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   channel.UsersTable,
			Columns: channel.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.OwnerUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerUserTable,
			Columns: []string{channel.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OwnerUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channel.OwnerUserTable,
			Columns: []string{channel.OwnerUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Channel{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
