// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/chat"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatCreate is the builder for creating a Chat entity.
type ChatCreate struct {
	config
	mutation *ChatMutation
	hooks    []Hook
}

// SetCreateTime sets the "createTime" field.
func (cc *ChatCreate) SetCreateTime(t time.Time) *ChatCreate {
	cc.mutation.SetCreateTime(t)
	return cc
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (cc *ChatCreate) SetNillableCreateTime(t *time.Time) *ChatCreate {
	if t != nil {
		cc.SetCreateTime(*t)
	}
	return cc
}

// SetUpdateTime sets the "updateTime" field.
func (cc *ChatCreate) SetUpdateTime(t time.Time) *ChatCreate {
	cc.mutation.SetUpdateTime(t)
	return cc
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (cc *ChatCreate) SetNillableUpdateTime(t *time.Time) *ChatCreate {
	if t != nil {
		cc.SetUpdateTime(*t)
	}
	return cc
}

// SetDeleteTime sets the "delete_time" field.
func (cc *ChatCreate) SetDeleteTime(t time.Time) *ChatCreate {
	cc.mutation.SetDeleteTime(t)
	return cc
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (cc *ChatCreate) SetNillableDeleteTime(t *time.Time) *ChatCreate {
	if t != nil {
		cc.SetDeleteTime(*t)
	}
	return cc
}

// SetBusinessType sets the "businessType" field.
func (cc *ChatCreate) SetBusinessType(ct chat.BusinessType) *ChatCreate {
	cc.mutation.SetBusinessType(ct)
	return cc
}

// SetBusinessID sets the "business_id" field.
func (cc *ChatCreate) SetBusinessID(s string) *ChatCreate {
	cc.mutation.SetBusinessID(s)
	return cc
}

// SetFromUserId sets the "fromUserId" field.
func (cc *ChatCreate) SetFromUserId(s string) *ChatCreate {
	cc.mutation.SetFromUserId(s)
	return cc
}

// SetSourceType sets the "sourceType" field.
func (cc *ChatCreate) SetSourceType(ct chat.SourceType) *ChatCreate {
	cc.mutation.SetSourceType(ct)
	return cc
}

// SetContentType sets the "contentType" field.
func (cc *ChatCreate) SetContentType(ct chat.ContentType) *ChatCreate {
	cc.mutation.SetContentType(ct)
	return cc
}

// SetContent sets the "content" field.
func (cc *ChatCreate) SetContent(s string) *ChatCreate {
	cc.mutation.SetContent(s)
	return cc
}

// SetID sets the "id" field.
func (cc *ChatCreate) SetID(i int64) *ChatCreate {
	cc.mutation.SetID(i)
	return cc
}

// Mutation returns the ChatMutation object of the builder.
func (cc *ChatCreate) Mutation() *ChatMutation {
	return cc.mutation
}

// Save creates the Chat in the database.
func (cc *ChatCreate) Save(ctx context.Context) (*Chat, error) {
	if err := cc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChatCreate) SaveX(ctx context.Context) *Chat {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ChatCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ChatCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ChatCreate) defaults() error {
	if _, ok := cc.mutation.CreateTime(); !ok {
		if chat.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized chat.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := chat.DefaultCreateTime()
		cc.mutation.SetCreateTime(v)
	}
	if _, ok := cc.mutation.UpdateTime(); !ok {
		if chat.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized chat.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := chat.DefaultUpdateTime()
		cc.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChatCreate) check() error {
	if _, ok := cc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "Chat.createTime"`)}
	}
	if _, ok := cc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "Chat.updateTime"`)}
	}
	if _, ok := cc.mutation.BusinessType(); !ok {
		return &ValidationError{Name: "businessType", err: errors.New(`ent: missing required field "Chat.businessType"`)}
	}
	if v, ok := cc.mutation.BusinessType(); ok {
		if err := chat.BusinessTypeValidator(v); err != nil {
			return &ValidationError{Name: "businessType", err: fmt.Errorf(`ent: validator failed for field "Chat.businessType": %w`, err)}
		}
	}
	if _, ok := cc.mutation.BusinessID(); !ok {
		return &ValidationError{Name: "business_id", err: errors.New(`ent: missing required field "Chat.business_id"`)}
	}
	if v, ok := cc.mutation.BusinessID(); ok {
		if err := chat.BusinessIDValidator(v); err != nil {
			return &ValidationError{Name: "business_id", err: fmt.Errorf(`ent: validator failed for field "Chat.business_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.FromUserId(); !ok {
		return &ValidationError{Name: "fromUserId", err: errors.New(`ent: missing required field "Chat.fromUserId"`)}
	}
	if v, ok := cc.mutation.FromUserId(); ok {
		if err := chat.FromUserIdValidator(v); err != nil {
			return &ValidationError{Name: "fromUserId", err: fmt.Errorf(`ent: validator failed for field "Chat.fromUserId": %w`, err)}
		}
	}
	if _, ok := cc.mutation.SourceType(); !ok {
		return &ValidationError{Name: "sourceType", err: errors.New(`ent: missing required field "Chat.sourceType"`)}
	}
	if v, ok := cc.mutation.SourceType(); ok {
		if err := chat.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "sourceType", err: fmt.Errorf(`ent: validator failed for field "Chat.sourceType": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ContentType(); !ok {
		return &ValidationError{Name: "contentType", err: errors.New(`ent: missing required field "Chat.contentType"`)}
	}
	if v, ok := cc.mutation.ContentType(); ok {
		if err := chat.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "contentType", err: fmt.Errorf(`ent: validator failed for field "Chat.contentType": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Chat.content"`)}
	}
	return nil
}

func (cc *ChatCreate) sqlSave(ctx context.Context) (*Chat, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ChatCreate) createSpec() (*Chat, *sqlgraph.CreateSpec) {
	var (
		_node = &Chat{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(chat.Table, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt64))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.CreateTime(); ok {
		_spec.SetField(chat.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := cc.mutation.UpdateTime(); ok {
		_spec.SetField(chat.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := cc.mutation.DeleteTime(); ok {
		_spec.SetField(chat.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = value
	}
	if value, ok := cc.mutation.BusinessType(); ok {
		_spec.SetField(chat.FieldBusinessType, field.TypeEnum, value)
		_node.BusinessType = value
	}
	if value, ok := cc.mutation.BusinessID(); ok {
		_spec.SetField(chat.FieldBusinessID, field.TypeString, value)
		_node.BusinessID = value
	}
	if value, ok := cc.mutation.FromUserId(); ok {
		_spec.SetField(chat.FieldFromUserId, field.TypeString, value)
		_node.FromUserId = value
	}
	if value, ok := cc.mutation.SourceType(); ok {
		_spec.SetField(chat.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := cc.mutation.ContentType(); ok {
		_spec.SetField(chat.FieldContentType, field.TypeEnum, value)
		_node.ContentType = value
	}
	if value, ok := cc.mutation.Content(); ok {
		_spec.SetField(chat.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	return _node, _spec
}

// ChatCreateBulk is the builder for creating many Chat entities in bulk.
type ChatCreateBulk struct {
	config
	builders []*ChatCreate
}

// Save creates the Chat entities in the database.
func (ccb *ChatCreateBulk) Save(ctx context.Context) ([]*Chat, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Chat, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChatCreateBulk) SaveX(ctx context.Context) []*Chat {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ChatCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ChatCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
