// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"server/ent/predicate"
	"server/ent/usernickname"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserNicknameDelete is the builder for deleting a UserNickname entity.
type UserNicknameDelete struct {
	config
	hooks    []Hook
	mutation *UserNicknameMutation
}

// Where appends a list predicates to the UserNicknameDelete builder.
func (und *UserNicknameDelete) Where(ps ...predicate.UserNickname) *UserNicknameDelete {
	und.mutation.Where(ps...)
	return und
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (und *UserNicknameDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, und.sqlExec, und.mutation, und.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (und *UserNicknameDelete) ExecX(ctx context.Context) int {
	n, err := und.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (und *UserNicknameDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usernickname.Table, sqlgraph.NewFieldSpec(usernickname.FieldID, field.TypeInt64))
	if ps := und.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, und.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	und.mutation.done = true
	return affected, err
}

// UserNicknameDeleteOne is the builder for deleting a single UserNickname entity.
type UserNicknameDeleteOne struct {
	und *UserNicknameDelete
}

// Where appends a list predicates to the UserNicknameDelete builder.
func (undo *UserNicknameDeleteOne) Where(ps ...predicate.UserNickname) *UserNicknameDeleteOne {
	undo.und.mutation.Where(ps...)
	return undo
}

// Exec executes the deletion query.
func (undo *UserNicknameDeleteOne) Exec(ctx context.Context) error {
	n, err := undo.und.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usernickname.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (undo *UserNicknameDeleteOne) ExecX(ctx context.Context) {
	if err := undo.Exec(ctx); err != nil {
		panic(err)
	}
}
