// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"server/ent/predicate"
	"server/ent/usernickname"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserNicknameQuery is the builder for querying UserNickname entities.
type UserNicknameQuery struct {
	config
	ctx        *QueryContext
	order      []usernickname.OrderOption
	inters     []Interceptor
	predicates []predicate.UserNickname
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserNicknameQuery builder.
func (unq *UserNicknameQuery) Where(ps ...predicate.UserNickname) *UserNicknameQuery {
	unq.predicates = append(unq.predicates, ps...)
	return unq
}

// Limit the number of records to be returned by this query.
func (unq *UserNicknameQuery) Limit(limit int) *UserNicknameQuery {
	unq.ctx.Limit = &limit
	return unq
}

// Offset to start from.
func (unq *UserNicknameQuery) Offset(offset int) *UserNicknameQuery {
	unq.ctx.Offset = &offset
	return unq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (unq *UserNicknameQuery) Unique(unique bool) *UserNicknameQuery {
	unq.ctx.Unique = &unique
	return unq
}

// Order specifies how the records should be ordered.
func (unq *UserNicknameQuery) Order(o ...usernickname.OrderOption) *UserNicknameQuery {
	unq.order = append(unq.order, o...)
	return unq
}

// First returns the first UserNickname entity from the query.
// Returns a *NotFoundError when no UserNickname was found.
func (unq *UserNicknameQuery) First(ctx context.Context) (*UserNickname, error) {
	nodes, err := unq.Limit(1).All(setContextOp(ctx, unq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usernickname.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (unq *UserNicknameQuery) FirstX(ctx context.Context) *UserNickname {
	node, err := unq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserNickname ID from the query.
// Returns a *NotFoundError when no UserNickname ID was found.
func (unq *UserNicknameQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = unq.Limit(1).IDs(setContextOp(ctx, unq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usernickname.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (unq *UserNicknameQuery) FirstIDX(ctx context.Context) int64 {
	id, err := unq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserNickname entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserNickname entity is found.
// Returns a *NotFoundError when no UserNickname entities are found.
func (unq *UserNicknameQuery) Only(ctx context.Context) (*UserNickname, error) {
	nodes, err := unq.Limit(2).All(setContextOp(ctx, unq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usernickname.Label}
	default:
		return nil, &NotSingularError{usernickname.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (unq *UserNicknameQuery) OnlyX(ctx context.Context) *UserNickname {
	node, err := unq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserNickname ID in the query.
// Returns a *NotSingularError when more than one UserNickname ID is found.
// Returns a *NotFoundError when no entities are found.
func (unq *UserNicknameQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = unq.Limit(2).IDs(setContextOp(ctx, unq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usernickname.Label}
	default:
		err = &NotSingularError{usernickname.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (unq *UserNicknameQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := unq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserNicknames.
func (unq *UserNicknameQuery) All(ctx context.Context) ([]*UserNickname, error) {
	ctx = setContextOp(ctx, unq.ctx, "All")
	if err := unq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserNickname, *UserNicknameQuery]()
	return withInterceptors[[]*UserNickname](ctx, unq, qr, unq.inters)
}

// AllX is like All, but panics if an error occurs.
func (unq *UserNicknameQuery) AllX(ctx context.Context) []*UserNickname {
	nodes, err := unq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserNickname IDs.
func (unq *UserNicknameQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if unq.ctx.Unique == nil && unq.path != nil {
		unq.Unique(true)
	}
	ctx = setContextOp(ctx, unq.ctx, "IDs")
	if err = unq.Select(usernickname.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (unq *UserNicknameQuery) IDsX(ctx context.Context) []int64 {
	ids, err := unq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (unq *UserNicknameQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, unq.ctx, "Count")
	if err := unq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, unq, querierCount[*UserNicknameQuery](), unq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (unq *UserNicknameQuery) CountX(ctx context.Context) int {
	count, err := unq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (unq *UserNicknameQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, unq.ctx, "Exist")
	switch _, err := unq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (unq *UserNicknameQuery) ExistX(ctx context.Context) bool {
	exist, err := unq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserNicknameQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (unq *UserNicknameQuery) Clone() *UserNicknameQuery {
	if unq == nil {
		return nil
	}
	return &UserNicknameQuery{
		config:     unq.config,
		ctx:        unq.ctx.Clone(),
		order:      append([]usernickname.OrderOption{}, unq.order...),
		inters:     append([]Interceptor{}, unq.inters...),
		predicates: append([]predicate.UserNickname{}, unq.predicates...),
		// clone intermediate query.
		sql:  unq.sql.Clone(),
		path: unq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserNickname.Query().
//		GroupBy(usernickname.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (unq *UserNicknameQuery) GroupBy(field string, fields ...string) *UserNicknameGroupBy {
	unq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserNicknameGroupBy{build: unq}
	grbuild.flds = &unq.ctx.Fields
	grbuild.label = usernickname.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.UserNickname.Query().
//		Select(usernickname.FieldCreateTime).
//		Scan(ctx, &v)
func (unq *UserNicknameQuery) Select(fields ...string) *UserNicknameSelect {
	unq.ctx.Fields = append(unq.ctx.Fields, fields...)
	sbuild := &UserNicknameSelect{UserNicknameQuery: unq}
	sbuild.label = usernickname.Label
	sbuild.flds, sbuild.scan = &unq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserNicknameSelect configured with the given aggregations.
func (unq *UserNicknameQuery) Aggregate(fns ...AggregateFunc) *UserNicknameSelect {
	return unq.Select().Aggregate(fns...)
}

func (unq *UserNicknameQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range unq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, unq); err != nil {
				return err
			}
		}
	}
	for _, f := range unq.ctx.Fields {
		if !usernickname.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if unq.path != nil {
		prev, err := unq.path(ctx)
		if err != nil {
			return err
		}
		unq.sql = prev
	}
	return nil
}

func (unq *UserNicknameQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserNickname, error) {
	var (
		nodes = []*UserNickname{}
		_spec = unq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserNickname).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserNickname{config: unq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, unq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (unq *UserNicknameQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := unq.querySpec()
	_spec.Node.Columns = unq.ctx.Fields
	if len(unq.ctx.Fields) > 0 {
		_spec.Unique = unq.ctx.Unique != nil && *unq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, unq.driver, _spec)
}

func (unq *UserNicknameQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usernickname.Table, usernickname.Columns, sqlgraph.NewFieldSpec(usernickname.FieldID, field.TypeInt64))
	_spec.From = unq.sql
	if unique := unq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if unq.path != nil {
		_spec.Unique = true
	}
	if fields := unq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usernickname.FieldID)
		for i := range fields {
			if fields[i] != usernickname.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := unq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := unq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := unq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := unq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (unq *UserNicknameQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(unq.driver.Dialect())
	t1 := builder.Table(usernickname.Table)
	columns := unq.ctx.Fields
	if len(columns) == 0 {
		columns = usernickname.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if unq.sql != nil {
		selector = unq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if unq.ctx.Unique != nil && *unq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range unq.predicates {
		p(selector)
	}
	for _, p := range unq.order {
		p(selector)
	}
	if offset := unq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := unq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserNicknameGroupBy is the group-by builder for UserNickname entities.
type UserNicknameGroupBy struct {
	selector
	build *UserNicknameQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ungb *UserNicknameGroupBy) Aggregate(fns ...AggregateFunc) *UserNicknameGroupBy {
	ungb.fns = append(ungb.fns, fns...)
	return ungb
}

// Scan applies the selector query and scans the result into the given value.
func (ungb *UserNicknameGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ungb.build.ctx, "GroupBy")
	if err := ungb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserNicknameQuery, *UserNicknameGroupBy](ctx, ungb.build, ungb, ungb.build.inters, v)
}

func (ungb *UserNicknameGroupBy) sqlScan(ctx context.Context, root *UserNicknameQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ungb.fns))
	for _, fn := range ungb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ungb.flds)+len(ungb.fns))
		for _, f := range *ungb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ungb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ungb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserNicknameSelect is the builder for selecting fields of UserNickname entities.
type UserNicknameSelect struct {
	*UserNicknameQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uns *UserNicknameSelect) Aggregate(fns ...AggregateFunc) *UserNicknameSelect {
	uns.fns = append(uns.fns, fns...)
	return uns
}

// Scan applies the selector query and scans the result into the given value.
func (uns *UserNicknameSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uns.ctx, "Select")
	if err := uns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserNicknameQuery, *UserNicknameSelect](ctx, uns.UserNicknameQuery, uns, uns.inters, v)
}

func (uns *UserNicknameSelect) sqlScan(ctx context.Context, root *UserNicknameQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uns.fns))
	for _, fn := range uns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
