version: "3.7"
services:
  db:
    image: mysql:8.1.0
    restart: always
    environment:
      - MYSQL_DATABASE=mic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./temp/db-data:/var/lib/mysql
