version: "3.7"
services:
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./data/files:/www/files
      - ./data/client-web:/www/web
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - 8999:80
    links:
      - server

  server:
    # build:
    #   context: ./
    #   dockerfile: ./docker/server/Dockerfile
    #   args:
    #     API_HOST: /api
    image: smilecc/mictory-server:latest
    environment:
      APP_ENV: prod
      APP_SECRET_PATH: /app/config/secret
      IP_ADDRESS: "127.0.0.1"
      DATABASE_URL: mysql://root:root@db:3306/mic
    volumes:
      - ./data/files:/app/packages/server/files
      - ./data/config:/app/config
      - ./data/client-web:/app/client-web-dist
    ports:
      - 55555:55555
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: mysql:8.1.0
    restart: always
    environment:
      - MYSQL_DATABASE=mic
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/var/lib/mysql
    # # recommend: Don't export the 3306 port for security reasons
    # ports:
    #   - 13306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50
