// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)
