// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"server/ent/channel"
	"server/ent/chat"
	"server/ent/room"
	"server/ent/schema"
	"server/ent/user"
	"server/ent/usernickname"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelMixin := schema.Channel{}.Mixin()
	channelMixinHooks1 := channelMixin[1].Hooks()
	channel.Hooks[0] = channelMixinHooks1[0]
	channelMixinInters1 := channelMixin[1].Interceptors()
	channel.Interceptors[0] = channelMixinInters1[0]
	channelMixinFields0 := channelMixin[0].Fields()
	_ = channelMixinFields0
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescCreateTime is the schema descriptor for createTime field.
	channelDescCreateTime := channelMixinFields0[0].Descriptor()
	// channel.DefaultCreateTime holds the default value on creation for the createTime field.
	channel.DefaultCreateTime = channelDescCreateTime.Default.(func() time.Time)
	// channelDescUpdateTime is the schema descriptor for updateTime field.
	channelDescUpdateTime := channelMixinFields0[1].Descriptor()
	// channel.DefaultUpdateTime holds the default value on creation for the updateTime field.
	channel.DefaultUpdateTime = channelDescUpdateTime.Default.(func() time.Time)
	// channel.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	channel.UpdateDefaultUpdateTime = channelDescUpdateTime.UpdateDefault.(func() time.Time)
	// channelDescCode is the schema descriptor for code field.
	channelDescCode := channelFields[1].Descriptor()
	// channel.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	channel.CodeValidator = channelDescCode.Validators[0].(func(string) error)
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[2].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = channelDescName.Validators[0].(func(string) error)
	chatMixin := schema.Chat{}.Mixin()
	chatMixinHooks1 := chatMixin[1].Hooks()
	chat.Hooks[0] = chatMixinHooks1[0]
	chatMixinInters1 := chatMixin[1].Interceptors()
	chat.Interceptors[0] = chatMixinInters1[0]
	chatMixinFields0 := chatMixin[0].Fields()
	_ = chatMixinFields0
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreateTime is the schema descriptor for createTime field.
	chatDescCreateTime := chatMixinFields0[0].Descriptor()
	// chat.DefaultCreateTime holds the default value on creation for the createTime field.
	chat.DefaultCreateTime = chatDescCreateTime.Default.(func() time.Time)
	// chatDescUpdateTime is the schema descriptor for updateTime field.
	chatDescUpdateTime := chatMixinFields0[1].Descriptor()
	// chat.DefaultUpdateTime holds the default value on creation for the updateTime field.
	chat.DefaultUpdateTime = chatDescUpdateTime.Default.(func() time.Time)
	// chat.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	chat.UpdateDefaultUpdateTime = chatDescUpdateTime.UpdateDefault.(func() time.Time)
	// chatDescBusinessID is the schema descriptor for business_id field.
	chatDescBusinessID := chatFields[2].Descriptor()
	// chat.BusinessIDValidator is a validator for the "business_id" field. It is called by the builders before save.
	chat.BusinessIDValidator = chatDescBusinessID.Validators[0].(func(string) error)
	// chatDescFromUserId is the schema descriptor for fromUserId field.
	chatDescFromUserId := chatFields[3].Descriptor()
	// chat.FromUserIdValidator is a validator for the "fromUserId" field. It is called by the builders before save.
	chat.FromUserIdValidator = chatDescFromUserId.Validators[0].(func(string) error)
	roomMixin := schema.Room{}.Mixin()
	roomMixinHooks1 := roomMixin[1].Hooks()
	room.Hooks[0] = roomMixinHooks1[0]
	roomMixinInters1 := roomMixin[1].Interceptors()
	room.Interceptors[0] = roomMixinInters1[0]
	roomMixinFields0 := roomMixin[0].Fields()
	_ = roomMixinFields0
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescCreateTime is the schema descriptor for createTime field.
	roomDescCreateTime := roomMixinFields0[0].Descriptor()
	// room.DefaultCreateTime holds the default value on creation for the createTime field.
	room.DefaultCreateTime = roomDescCreateTime.Default.(func() time.Time)
	// roomDescUpdateTime is the schema descriptor for updateTime field.
	roomDescUpdateTime := roomMixinFields0[1].Descriptor()
	// room.DefaultUpdateTime holds the default value on creation for the updateTime field.
	room.DefaultUpdateTime = roomDescUpdateTime.Default.(func() time.Time)
	// room.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	room.UpdateDefaultUpdateTime = roomDescUpdateTime.UpdateDefault.(func() time.Time)
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[1].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = roomDescName.Validators[0].(func(string) error)
	// roomDescMaxMember is the schema descriptor for maxMember field.
	roomDescMaxMember := roomFields[2].Descriptor()
	// room.DefaultMaxMember holds the default value on creation for the maxMember field.
	room.DefaultMaxMember = roomDescMaxMember.Default.(int32)
	// roomDescSort is the schema descriptor for sort field.
	roomDescSort := roomFields[3].Descriptor()
	// room.DefaultSort holds the default value on creation for the sort field.
	room.DefaultSort = roomDescSort.Default.(int32)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for createTime field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the createTime field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for updateTime field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the updateTime field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[4].Descriptor()
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[6].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPasswordSalt is the schema descriptor for password_salt field.
	userDescPasswordSalt := userFields[7].Descriptor()
	// user.PasswordSaltValidator is a validator for the "password_salt" field. It is called by the builders before save.
	user.PasswordSaltValidator = userDescPasswordSalt.Validators[0].(func(string) error)
	usernicknameMixin := schema.UserNickname{}.Mixin()
	usernicknameMixinHooks1 := usernicknameMixin[1].Hooks()
	usernickname.Hooks[0] = usernicknameMixinHooks1[0]
	usernicknameMixinInters1 := usernicknameMixin[1].Interceptors()
	usernickname.Interceptors[0] = usernicknameMixinInters1[0]
	usernicknameMixinFields0 := usernicknameMixin[0].Fields()
	_ = usernicknameMixinFields0
	usernicknameFields := schema.UserNickname{}.Fields()
	_ = usernicknameFields
	// usernicknameDescCreateTime is the schema descriptor for createTime field.
	usernicknameDescCreateTime := usernicknameMixinFields0[0].Descriptor()
	// usernickname.DefaultCreateTime holds the default value on creation for the createTime field.
	usernickname.DefaultCreateTime = usernicknameDescCreateTime.Default.(func() time.Time)
	// usernicknameDescUpdateTime is the schema descriptor for updateTime field.
	usernicknameDescUpdateTime := usernicknameMixinFields0[1].Descriptor()
	// usernickname.DefaultUpdateTime holds the default value on creation for the updateTime field.
	usernickname.DefaultUpdateTime = usernicknameDescUpdateTime.Default.(func() time.Time)
	// usernickname.UpdateDefaultUpdateTime holds the default value on update for the updateTime field.
	usernickname.UpdateDefaultUpdateTime = usernicknameDescUpdateTime.UpdateDefault.(func() time.Time)
	// usernicknameDescNickname is the schema descriptor for nickname field.
	usernicknameDescNickname := usernicknameFields[1].Descriptor()
	// usernickname.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	usernickname.NicknameValidator = usernicknameDescNickname.Validators[0].(func(string) error)
}

const (
	Version = "v0.12.3"                                         // Version of ent codegen.
	Sum     = "h1:N5lO2EOrHpCH5HYfiMOCHYbo+oh5M8GjT0/cx5x6xkk=" // Sum of ent codegen.
)
