// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"server/ent/channel"
	"server/ent/room"
	"server/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelMixin := schema.Channel{}.Mixin()
	channelMixinHooks1 := channelMixin[1].Hooks()
	channel.Hooks[0] = channelMixinHooks1[0]
	channelMixinInters1 := channelMixin[1].Interceptors()
	channel.Interceptors[0] = channelMixinInters1[0]
	channelMixinFields0 := channelMixin[0].Fields()
	_ = channelMixinFields0
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescCreateTime is the schema descriptor for create_time field.
	channelDescCreateTime := channelMixinFields0[0].Descriptor()
	// channel.DefaultCreateTime holds the default value on creation for the create_time field.
	channel.DefaultCreateTime = channelDescCreateTime.Default.(func() time.Time)
	// channelDescUpdateTime is the schema descriptor for update_time field.
	channelDescUpdateTime := channelMixinFields0[1].Descriptor()
	// channel.DefaultUpdateTime holds the default value on creation for the update_time field.
	channel.DefaultUpdateTime = channelDescUpdateTime.Default.(func() time.Time)
	// channel.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	channel.UpdateDefaultUpdateTime = channelDescUpdateTime.UpdateDefault.(func() time.Time)
	// channelDescCode is the schema descriptor for code field.
	channelDescCode := channelFields[1].Descriptor()
	// channel.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	channel.CodeValidator = channelDescCode.Validators[0].(func(string) error)
	// channelDescName is the schema descriptor for name field.
	channelDescName := channelFields[2].Descriptor()
	// channel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	channel.NameValidator = channelDescName.Validators[0].(func(string) error)
	roomMixin := schema.Room{}.Mixin()
	roomMixinHooks1 := roomMixin[1].Hooks()
	room.Hooks[0] = roomMixinHooks1[0]
	roomMixinInters1 := roomMixin[1].Interceptors()
	room.Interceptors[0] = roomMixinInters1[0]
	roomMixinFields0 := roomMixin[0].Fields()
	_ = roomMixinFields0
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescCreateTime is the schema descriptor for create_time field.
	roomDescCreateTime := roomMixinFields0[0].Descriptor()
	// room.DefaultCreateTime holds the default value on creation for the create_time field.
	room.DefaultCreateTime = roomDescCreateTime.Default.(func() time.Time)
	// roomDescUpdateTime is the schema descriptor for update_time field.
	roomDescUpdateTime := roomMixinFields0[1].Descriptor()
	// room.DefaultUpdateTime holds the default value on creation for the update_time field.
	room.DefaultUpdateTime = roomDescUpdateTime.Default.(func() time.Time)
	// room.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	room.UpdateDefaultUpdateTime = roomDescUpdateTime.UpdateDefault.(func() time.Time)
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[1].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = roomDescName.Validators[0].(func(string) error)
	// roomDescMaxMember is the schema descriptor for max_member field.
	roomDescMaxMember := roomFields[2].Descriptor()
	// room.DefaultMaxMember holds the default value on creation for the max_member field.
	room.DefaultMaxMember = roomDescMaxMember.Default.(int)
	// roomDescSort is the schema descriptor for sort field.
	roomDescSort := roomFields[3].Descriptor()
	// room.DefaultSort holds the default value on creation for the sort field.
	room.DefaultSort = roomDescSort.Default.(int)
}

const (
	Version = "v0.12.3"                                         // Version of ent codegen.
	Sum     = "h1:N5lO2EOrHpCH5HYfiMOCHYbo+oh5M8GjT0/cx5x6xkk=" // Sum of ent codegen.
)
