// Code generated by ent, DO NOT EDIT.

package chat

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chat type in the database.
	Label = "chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the createtime field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the updatetime field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldBusinessType holds the string denoting the businesstype field in the database.
	FieldBusinessType = "business_type"
	// FieldBusinessID holds the string denoting the business_id field in the database.
	FieldBusinessID = "business_id"
	// FieldFromUserId holds the string denoting the fromuserid field in the database.
	FieldFromUserId = "from_user_id"
	// FieldSourceType holds the string denoting the sourcetype field in the database.
	FieldSourceType = "source_type"
	// FieldContentType holds the string denoting the contenttype field in the database.
	FieldContentType = "content_type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// Table holds the table name of the chat in the database.
	Table = "chats"
)

// Columns holds all SQL columns for chat fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldBusinessType,
	FieldBusinessID,
	FieldFromUserId,
	FieldSourceType,
	FieldContentType,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "server/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreateTime holds the default value on creation for the "createTime" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "updateTime" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "updateTime" field.
	UpdateDefaultUpdateTime func() time.Time
	// BusinessIDValidator is a validator for the "business_id" field. It is called by the builders before save.
	BusinessIDValidator func(string) error
	// FromUserIdValidator is a validator for the "fromUserId" field. It is called by the builders before save.
	FromUserIdValidator func(string) error
)

// BusinessType defines the type for the "businessType" enum field.
type BusinessType string

// BusinessType values.
const (
	BusinessTypeRoom BusinessType = "room"
	BusinessTypeUser BusinessType = "user"
)

func (bt BusinessType) String() string {
	return string(bt)
}

// BusinessTypeValidator is a validator for the "businessType" field enum values. It is called by the builders before save.
func BusinessTypeValidator(bt BusinessType) error {
	switch bt {
	case BusinessTypeRoom, BusinessTypeUser:
		return nil
	default:
		return fmt.Errorf("chat: invalid enum value for businessType field: %q", bt)
	}
}

// SourceType defines the type for the "sourceType" enum field.
type SourceType string

// SourceType values.
const (
	SourceTypeSystem SourceType = "system"
	SourceTypeAdmin  SourceType = "admin"
	SourceTypeUser   SourceType = "user"
)

func (st SourceType) String() string {
	return string(st)
}

// SourceTypeValidator is a validator for the "sourceType" field enum values. It is called by the builders before save.
func SourceTypeValidator(st SourceType) error {
	switch st {
	case SourceTypeSystem, SourceTypeAdmin, SourceTypeUser:
		return nil
	default:
		return fmt.Errorf("chat: invalid enum value for sourceType field: %q", st)
	}
}

// ContentType defines the type for the "contentType" enum field.
type ContentType string

// ContentType values.
const (
	ContentTypeText  ContentType = "text"
	ContentTypeImage ContentType = "image"
)

func (ct ContentType) String() string {
	return string(ct)
}

// ContentTypeValidator is a validator for the "contentType" field enum values. It is called by the builders before save.
func ContentTypeValidator(ct ContentType) error {
	switch ct {
	case ContentTypeText, ContentTypeImage:
		return nil
	default:
		return fmt.Errorf("chat: invalid enum value for contentType field: %q", ct)
	}
}

// OrderOption defines the ordering options for the Chat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the createTime field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the updateTime field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByBusinessType orders the results by the businessType field.
func ByBusinessType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessType, opts...).ToFunc()
}

// ByBusinessID orders the results by the business_id field.
func ByBusinessID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessID, opts...).ToFunc()
}

// ByFromUserId orders the results by the fromUserId field.
func ByFromUserId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromUserId, opts...).ToFunc()
}

// BySourceType orders the results by the sourceType field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// ByContentType orders the results by the contentType field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}
